// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package clients

// ControllerV1 clients controller 客户端控制器
type ControllerV1 struct{}

// NewV1 creates clients controller 创建客户端控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
