// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package taskrecords

// ControllerV1 task records controller 任务记录控制器
type ControllerV1 struct{}

// NewV1 creates task records controller 创建任务记录控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
