// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ws

// ControllerV1 websocket controller 长连接控制器
type ControllerV1 struct{}

// NewV1 creates websocket controller 创建长连接控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
