// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package browserexecutor

// ControllerV1 browser executor controller. 浏览器执行器控制器。
type ControllerV1 struct{}

// NewV1 creates browser executor controller 閸掓稑缂撳ù蹇氼潔閸ｃ劍澧界悰灞芥珤閹貉冨煑閸?
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
