/*
 Navicat Premium Dump SQL

 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Catalog        : browserflow
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 24/05/2026
*/


-- ----------------------------
-- Drop tables
-- ----------------------------
DROP TABLE IF EXISTS "public"."node_events" CASCADE;
DROP TABLE IF EXISTS "public"."node_commands" CASCADE;
DROP TABLE IF EXISTS "public"."node_packages" CASCADE;
DROP TABLE IF EXISTS "public"."node_workflows" CASCADE;
DROP TABLE IF EXISTS "public"."node_group_members" CASCADE;
DROP TABLE IF EXISTS "public"."node_groups" CASCADE;
DROP TABLE IF EXISTS "public"."task_attempts" CASCADE;
DROP TABLE IF EXISTS "public"."task_queue" CASCADE;
DROP TABLE IF EXISTS "public"."task_record_files" CASCADE;
DROP TABLE IF EXISTS "public"."task_records" CASCADE;
DROP TABLE IF EXISTS "public"."tasks" CASCADE;
DROP TABLE IF EXISTS "public"."automa_packages" CASCADE;
DROP TABLE IF EXISTS "public"."clients" CASCADE;
DROP TABLE IF EXISTS "public"."automa_workflows" CASCADE;

DROP SEQUENCE IF EXISTS "public"."node_events_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."node_commands_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."node_packages_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."node_workflows_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."node_group_members_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."node_groups_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."task_attempts_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."task_queue_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."task_record_files_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."task_records_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."tasks_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."automa_packages_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."clients_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "public"."automa_workflows_id_seq" CASCADE;


-- ----------------------------
-- Table structure for automa_workflows
-- ----------------------------
CREATE TABLE "public"."automa_workflows" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "automa_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "name" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "description" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "source" int4 NOT NULL DEFAULT 1,
  "source_ip" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "source_node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "source_user_agent" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "automa_version" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "ext_version" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "created_at_automa" int8 NOT NULL DEFAULT 0,
  "updated_at_automa" int8 NOT NULL DEFAULT 0,
  "is_disabled" bool NOT NULL DEFAULT false,
  "is_protected" bool NOT NULL DEFAULT false,
  "node_count" int4 NOT NULL DEFAULT 0,
  "edge_count" int4 NOT NULL DEFAULT 0,
  "raw_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "normalized_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "content_hash" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "revision" int4 NOT NULL DEFAULT 1,
  "first_synced_at" timestamptz(6),
  "last_synced_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6),
  "automa_name" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "automa_description" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text
)
;
COMMENT ON COLUMN "public"."automa_workflows"."id" IS '后端自增主键';
COMMENT ON COLUMN "public"."automa_workflows"."automa_id" IS 'Automa 原始工作流 ID，用于识别同一个工作流';
COMMENT ON COLUMN "public"."automa_workflows"."name" IS '服务端自定义工作流名称';
COMMENT ON COLUMN "public"."automa_workflows"."description" IS '服务端自定义工作流描述';
COMMENT ON COLUMN "public"."automa_workflows"."source" IS '来源：1 页面导入，2 客户端同步，3 服务端生成';
COMMENT ON COLUMN "public"."automa_workflows"."source_ip" IS '最后同步来源客户端 IP';
COMMENT ON COLUMN "public"."automa_workflows"."source_node_id" IS '最后同步来源执行节点 ID';
COMMENT ON COLUMN "public"."automa_workflows"."source_user_agent" IS '最后同步来源浏览器 User-Agent';
COMMENT ON COLUMN "public"."automa_workflows"."automa_version" IS '工作流保存时的 Automa 插件版本';
COMMENT ON COLUMN "public"."automa_workflows"."ext_version" IS 'Automa 导出文件中的 extVersion';
COMMENT ON COLUMN "public"."automa_workflows"."created_at_automa" IS 'Automa 原始 createdAt，通常为毫秒时间戳';
COMMENT ON COLUMN "public"."automa_workflows"."updated_at_automa" IS 'Automa 原始 updatedAt，通常为毫秒时间戳';
COMMENT ON COLUMN "public"."automa_workflows"."is_disabled" IS '是否被 Automa 禁用';
COMMENT ON COLUMN "public"."automa_workflows"."is_protected" IS '是否受保护，受保护工作流不允许客户端覆盖';
COMMENT ON COLUMN "public"."automa_workflows"."node_count" IS '工作流节点数量';
COMMENT ON COLUMN "public"."automa_workflows"."edge_count" IS '工作流连线数量';
COMMENT ON COLUMN "public"."automa_workflows"."raw_json" IS 'Automa 导出的原始完整 JSON';
COMMENT ON COLUMN "public"."automa_workflows"."normalized_json" IS '规范化后的工作流 JSON，用于内容比对和下发';
COMMENT ON COLUMN "public"."automa_workflows"."content_hash" IS '核心内容 hash，用于判断工作流是否变化';
COMMENT ON COLUMN "public"."automa_workflows"."revision" IS '服务端工作流版本号，内容变化时递增';
COMMENT ON COLUMN "public"."automa_workflows"."first_synced_at" IS '第一次同步到服务端的时间';
COMMENT ON COLUMN "public"."automa_workflows"."last_synced_at" IS '最近一次同步到服务端的时间';
COMMENT ON COLUMN "public"."automa_workflows"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."automa_workflows"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."automa_workflows"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "public"."automa_workflows"."automa_name" IS 'Automa 工作流 JSON 中的原始名称';
COMMENT ON COLUMN "public"."automa_workflows"."automa_description" IS 'Automa 工作流 JSON 中的原始描述';
COMMENT ON TABLE "public"."automa_workflows" IS '服务端工作流主表';

-- ----------------------------
-- Table structure for clients
-- ----------------------------
CREATE TABLE "public"."clients" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_index" int4 NOT NULL DEFAULT 0,
  "worker_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "profile_dir" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "extension_dir" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "user_agent" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'offline'::character varying,
  "busy_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'idle'::character varying,
  "current_execution_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "current_task_record_id" int8 NOT NULL DEFAULT 0,
  "plugin_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'unknown'::character varying,
  "automa_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "browser_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "browser_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "os_name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "os_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "hostname" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "capabilities_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_command_at" timestamptz(6),
  "last_workflow_sync_at" timestamptz(6),
  "last_lock_renewed_at" timestamptz(6),
  "is_banned" bool NOT NULL DEFAULT false,
  "ban_reason" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "first_seen_at" timestamptz(6) NOT NULL DEFAULT now(),
  "last_seen_at" timestamptz(6) NOT NULL DEFAULT now(),
  "connected_at" timestamptz(6),
  "disconnected_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."clients"."id" IS '主键 ID，自增';
COMMENT ON COLUMN "public"."clients"."client_ip" IS '客户端 IP';
COMMENT ON COLUMN "public"."clients"."node_id" IS '执行节点 ID，同一 IP 下唯一，例如 node-1、node-2';
COMMENT ON COLUMN "public"."clients"."node_index" IS 'Worker 本机节点序号';
COMMENT ON COLUMN "public"."clients"."worker_version" IS 'BrowserFlow Worker 客户端版本';
COMMENT ON COLUMN "public"."clients"."profile_dir" IS '执行节点使用的 Chrome 用户数据目录';
COMMENT ON COLUMN "public"."clients"."extension_dir" IS '执行节点加载的 Automa 插件目录';
COMMENT ON COLUMN "public"."clients"."user_agent" IS '客户端浏览器 User-Agent';
COMMENT ON COLUMN "public"."clients"."status" IS '客户端当前状态：online 在线，offline 离线';
COMMENT ON COLUMN "public"."clients"."busy_status" IS '节点忙闲状态：idle 空闲，busy 执行中，unknown 未知';
COMMENT ON COLUMN "public"."clients"."current_execution_id" IS '节点当前执行中的后端执行 ID';
COMMENT ON COLUMN "public"."clients"."current_task_record_id" IS '节点当前执行中的任务记录 ID';
COMMENT ON COLUMN "public"."clients"."plugin_status" IS 'Automa 插件状态：unknown、installed、not_installed、disabled、error';
COMMENT ON COLUMN "public"."clients"."automa_version" IS 'Automa 插件版本号';
COMMENT ON COLUMN "public"."clients"."browser_name" IS '浏览器名称，例如 Chrome、Edge';
COMMENT ON COLUMN "public"."clients"."browser_version" IS '浏览器版本号';
COMMENT ON COLUMN "public"."clients"."os_name" IS '操作系统名称，例如 Windows、macOS、Linux';
COMMENT ON COLUMN "public"."clients"."os_version" IS '操作系统版本号';
COMMENT ON COLUMN "public"."clients"."hostname" IS '客户端设备主机名';
COMMENT ON COLUMN "public"."clients"."capabilities_json" IS '节点能力快照，例如是否支持工作流安装、插件安装、文件回传';
COMMENT ON COLUMN "public"."clients"."last_command_at" IS '最近一次服务端命令下发时间';
COMMENT ON COLUMN "public"."clients"."last_workflow_sync_at" IS '最近一次工作流清单同步时间';
COMMENT ON COLUMN "public"."clients"."last_lock_renewed_at" IS '节点执行锁最近续期时间';
COMMENT ON COLUMN "public"."clients"."is_banned" IS '是否被拉黑，true 表示禁止使用';
COMMENT ON COLUMN "public"."clients"."ban_reason" IS '客户端被拉黑的原因';
COMMENT ON COLUMN "public"."clients"."first_seen_at" IS '第一次连接到服务端的时间';
COMMENT ON COLUMN "public"."clients"."last_seen_at" IS '最近一次心跳或交互时间';
COMMENT ON COLUMN "public"."clients"."connected_at" IS '最近一次建立 WebSocket 连接的时间';
COMMENT ON COLUMN "public"."clients"."disconnected_at" IS '最近一次断开 WebSocket 连接的时间';
COMMENT ON COLUMN "public"."clients"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."clients"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."clients"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."clients" IS '客户端执行节点表';


-- ----------------------------
-- Table structure for automa_packages
-- ----------------------------
CREATE TABLE "public"."automa_packages" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "package_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_path" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "file_size" int8 NOT NULL DEFAULT 0,
  "sha256" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "manifest_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'active'::character varying,
  "is_default" bool NOT NULL DEFAULT false,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."automa_packages"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."automa_packages"."package_name" IS '安装包名称，例如 Automa Chrome Extension';
COMMENT ON COLUMN "public"."automa_packages"."version" IS '安装包版本号';
COMMENT ON COLUMN "public"."automa_packages"."file_name" IS '原始文件名';
COMMENT ON COLUMN "public"."automa_packages"."file_path" IS '服务端存储路径';
COMMENT ON COLUMN "public"."automa_packages"."file_size" IS '文件大小，单位字节';
COMMENT ON COLUMN "public"."automa_packages"."sha256" IS '安装包 sha256 校验值';
COMMENT ON COLUMN "public"."automa_packages"."manifest_json" IS '插件 manifest 内容快照';
COMMENT ON COLUMN "public"."automa_packages"."status" IS '安装包状态：active 可用，disabled 禁用';
COMMENT ON COLUMN "public"."automa_packages"."is_default" IS '是否为默认下发版本';
COMMENT ON COLUMN "public"."automa_packages"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."automa_packages"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."automa_packages"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."automa_packages" IS 'Automa 插件安装包表';


-- ----------------------------
-- Table structure for tasks
-- ----------------------------
CREATE TABLE "public"."tasks" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "name" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "description" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "automa_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "target_group_id" int8 NOT NULL DEFAULT 0,
  "dispatch_mode" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'auto'::character varying,
  "queue_policy" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'queue'::character varying,
  "conflict_window_seconds" int4 NOT NULL DEFAULT 600,
  "max_attempts" int4 NOT NULL DEFAULT 1,
  "timeout_seconds" int4 NOT NULL DEFAULT 300,
  "cron_expression" varchar(120) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "enabled" bool NOT NULL DEFAULT true,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."tasks"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."tasks"."name" IS '任务名称';
COMMENT ON COLUMN "public"."tasks"."description" IS '任务说明';
COMMENT ON COLUMN "public"."tasks"."automa_id" IS 'Automa 原始工作流 ID';
COMMENT ON COLUMN "public"."tasks"."client_ip" IS '目标客户端 IP，为空表示由服务端自动选择';
COMMENT ON COLUMN "public"."tasks"."node_id" IS '目标执行节点 ID，为空表示由服务端选择可用节点';
COMMENT ON COLUMN "public"."tasks"."target_group_id" IS '目标节点分组 ID，为 0 表示不限定分组';
COMMENT ON COLUMN "public"."tasks"."dispatch_mode" IS '调度模式：auto 自动选择，group 指定分组，node 指定节点，ip 指定 IP';
COMMENT ON COLUMN "public"."tasks"."queue_policy" IS '繁忙策略：queue 排队，fail 直接失败，skip 跳过本次';
COMMENT ON COLUMN "public"."tasks"."conflict_window_seconds" IS '创建或编辑定时任务时用于冲突提醒的时间窗口秒数';
COMMENT ON COLUMN "public"."tasks"."max_attempts" IS '任务最多尝试次数';
COMMENT ON COLUMN "public"."tasks"."timeout_seconds" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "public"."tasks"."cron_expression" IS 'Cron 表达式，为空表示立即执行';
COMMENT ON COLUMN "public"."tasks"."params_json" IS '任务自定义参数快照，JSONB 存储';
COMMENT ON COLUMN "public"."tasks"."enabled" IS '是否启用';
COMMENT ON COLUMN "public"."tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "public"."tasks"."updated_at" IS '更新时间';
COMMENT ON COLUMN "public"."tasks"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."tasks" IS '任务配置表';


-- ----------------------------
-- Table structure for task_records
-- ----------------------------
CREATE TABLE "public"."task_records" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "task_id" int8 NOT NULL DEFAULT 0,
  "workflow_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "execution_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "automa_execution_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "command_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "queue_id" int8 NOT NULL DEFAULT 0,
  "attempt_no" int4 NOT NULL DEFAULT 0,
  "trigger_type" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'manual'::character varying,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "result_json" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "error_message" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "started_at" timestamptz(6),
  "finished_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."task_records"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."task_records"."task_id" IS '关联的任务配置 ID';
COMMENT ON COLUMN "public"."task_records"."workflow_id" IS '执行时使用的 Automa 工作流 ID';
COMMENT ON COLUMN "public"."task_records"."client_ip" IS '执行客户端 IP';
COMMENT ON COLUMN "public"."task_records"."node_id" IS '执行目标节点 ID';
COMMENT ON COLUMN "public"."task_records"."execution_id" IS '后端本次执行标识，用于客户端回调和状态恢复，例如 task-record-{id}';
COMMENT ON COLUMN "public"."task_records"."automa_execution_id" IS 'Automa 客户端侧本次执行实例 ID，例如 stateId 或 historyId';
COMMENT ON COLUMN "public"."task_records"."command_id" IS '对应下发给节点的命令 ID';
COMMENT ON COLUMN "public"."task_records"."queue_id" IS '对应的任务队列记录 ID';
COMMENT ON COLUMN "public"."task_records"."attempt_no" IS '第几次执行尝试';
COMMENT ON COLUMN "public"."task_records"."trigger_type" IS '触发类型：manual 手动触发，cron 定时触发，task_create 创建任务触发，skill Skill 触发，system 系统触发';
COMMENT ON COLUMN "public"."task_records"."status" IS '执行状态：pending、queued、running、success、failed、cancelled、timeout';
COMMENT ON COLUMN "public"."task_records"."params_json" IS '本次执行使用的参数快照';
COMMENT ON COLUMN "public"."task_records"."result_json" IS '本次执行结果内容';
COMMENT ON COLUMN "public"."task_records"."error_message" IS '执行失败时的错误信息';
COMMENT ON COLUMN "public"."task_records"."started_at" IS '开始执行时间';
COMMENT ON COLUMN "public"."task_records"."finished_at" IS '执行结束时间';
COMMENT ON COLUMN "public"."task_records"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."task_records"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."task_records"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."task_records" IS '任务执行记录表';


-- ----------------------------
-- Table structure for task_record_files
-- ----------------------------
CREATE TABLE "public"."task_record_files" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "record_id" int8 NOT NULL DEFAULT 0,
  "task_id" int8 NOT NULL DEFAULT 0,
  "workflow_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "execution_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_type" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_path" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "mime_type" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "file_size" int8 NOT NULL DEFAULT 0,
  "row_count" int4 NOT NULL DEFAULT 0,
  "preview_json" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "remark" varchar(512) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."task_record_files"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."task_record_files"."record_id" IS '关联任务执行记录 ID';
COMMENT ON COLUMN "public"."task_record_files"."task_id" IS '关联任务配置 ID';
COMMENT ON COLUMN "public"."task_record_files"."workflow_id" IS '执行时使用的 Automa 工作流 ID';
COMMENT ON COLUMN "public"."task_record_files"."client_ip" IS '执行客户端 IP';
COMMENT ON COLUMN "public"."task_record_files"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."task_record_files"."execution_id" IS '后端本次执行标识';
COMMENT ON COLUMN "public"."task_record_files"."file_type" IS '文件类型：table_json、table_csv、variables_json、log、screenshot 等';
COMMENT ON COLUMN "public"."task_record_files"."file_name" IS '原始或展示文件名';
COMMENT ON COLUMN "public"."task_record_files"."file_path" IS '服务端保存路径或对象存储 Key';
COMMENT ON COLUMN "public"."task_record_files"."mime_type" IS '文件 MIME 类型';
COMMENT ON COLUMN "public"."task_record_files"."file_size" IS '文件大小，单位字节';
COMMENT ON COLUMN "public"."task_record_files"."row_count" IS '表格结果行数';
COMMENT ON COLUMN "public"."task_record_files"."preview_json" IS '预览数据，例如前几行表格';
COMMENT ON COLUMN "public"."task_record_files"."remark" IS '备注';
COMMENT ON COLUMN "public"."task_record_files"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."task_record_files"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."task_record_files"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."task_record_files" IS '任务执行结果文件表';


-- ----------------------------
-- Table structure for task_queue
-- ----------------------------
CREATE TABLE "public"."task_queue" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "task_id" int8 NOT NULL DEFAULT 0,
  "workflow_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "dispatch_mode" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'auto'::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "target_group_id" int8 NOT NULL DEFAULT 0,
  "trigger_type" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'manual'::character varying,
  "priority" int4 NOT NULL DEFAULT 0,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "attempt_count" int4 NOT NULL DEFAULT 0,
  "max_attempts" int4 NOT NULL DEFAULT 1,
  "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_error" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "scheduled_at" timestamptz(6),
  "reserved_at" timestamptz(6),
  "started_at" timestamptz(6),
  "finished_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."task_queue"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."task_queue"."task_id" IS '关联任务配置 ID';
COMMENT ON COLUMN "public"."task_queue"."workflow_id" IS '待执行 Automa 工作流 ID';
COMMENT ON COLUMN "public"."task_queue"."dispatch_mode" IS '调度模式快照：auto、group、node、ip';
COMMENT ON COLUMN "public"."task_queue"."client_ip" IS '目标客户端 IP 快照';
COMMENT ON COLUMN "public"."task_queue"."node_id" IS '目标节点 ID';
COMMENT ON COLUMN "public"."task_queue"."target_group_id" IS '目标节点分组 ID';
COMMENT ON COLUMN "public"."task_queue"."trigger_type" IS '触发类型';
COMMENT ON COLUMN "public"."task_queue"."priority" IS '优先级，数字越大优先级越高';
COMMENT ON COLUMN "public"."task_queue"."status" IS '队列状态：pending、reserved、running、success、failed、cancelled、skipped';
COMMENT ON COLUMN "public"."task_queue"."attempt_count" IS '已尝试次数';
COMMENT ON COLUMN "public"."task_queue"."max_attempts" IS '最大尝试次数';
COMMENT ON COLUMN "public"."task_queue"."params_json" IS '本次排队任务参数快照';
COMMENT ON COLUMN "public"."task_queue"."last_error" IS '最近一次失败原因';
COMMENT ON COLUMN "public"."task_queue"."scheduled_at" IS '计划执行时间';
COMMENT ON COLUMN "public"."task_queue"."reserved_at" IS '被调度器占用时间';
COMMENT ON COLUMN "public"."task_queue"."started_at" IS '开始执行时间';
COMMENT ON COLUMN "public"."task_queue"."finished_at" IS '执行完成时间';
COMMENT ON COLUMN "public"."task_queue"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."task_queue"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."task_queue"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."task_queue" IS '任务调度队列表';


-- ----------------------------
-- Table structure for task_attempts
-- ----------------------------
CREATE TABLE "public"."task_attempts" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "queue_id" int8 NOT NULL DEFAULT 0,
  "task_id" int8 NOT NULL DEFAULT 0,
  "record_id" int8 NOT NULL DEFAULT 0,
  "attempt_no" int4 NOT NULL DEFAULT 1,
  "workflow_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "execution_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "command_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "error_message" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "started_at" timestamptz(6),
  "finished_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."task_attempts"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."task_attempts"."queue_id" IS '对应任务队列 ID';
COMMENT ON COLUMN "public"."task_attempts"."task_id" IS '关联任务配置 ID';
COMMENT ON COLUMN "public"."task_attempts"."record_id" IS '关联任务执行记录 ID';
COMMENT ON COLUMN "public"."task_attempts"."attempt_no" IS '尝试序号，从 1 开始';
COMMENT ON COLUMN "public"."task_attempts"."workflow_id" IS '执行工作流 ID';
COMMENT ON COLUMN "public"."task_attempts"."client_ip" IS '执行客户端 IP 快照';
COMMENT ON COLUMN "public"."task_attempts"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."task_attempts"."execution_id" IS '后端本次执行标识';
COMMENT ON COLUMN "public"."task_attempts"."command_id" IS '对应节点命令 ID';
COMMENT ON COLUMN "public"."task_attempts"."status" IS '尝试状态：pending、running、success、failed、timeout、cancelled';
COMMENT ON COLUMN "public"."task_attempts"."error_message" IS '本次尝试失败原因';
COMMENT ON COLUMN "public"."task_attempts"."started_at" IS '尝试开始时间';
COMMENT ON COLUMN "public"."task_attempts"."finished_at" IS '尝试结束时间';
COMMENT ON COLUMN "public"."task_attempts"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."task_attempts"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."task_attempts"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."task_attempts" IS '任务执行尝试表';


-- ----------------------------
-- Table structure for node_groups
-- ----------------------------
CREATE TABLE "public"."node_groups" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "group_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "description" varchar(512) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "enabled" bool NOT NULL DEFAULT true,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_groups"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_groups"."group_name" IS '节点分组名称，例如 财务组、客服组、闲置节点池';
COMMENT ON COLUMN "public"."node_groups"."description" IS '节点分组说明';
COMMENT ON COLUMN "public"."node_groups"."enabled" IS '是否启用该分组';
COMMENT ON COLUMN "public"."node_groups"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_groups"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_groups"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_groups" IS '执行节点分组表';


-- ----------------------------
-- Table structure for node_group_members
-- ----------------------------
CREATE TABLE "public"."node_group_members" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "group_id" int8 NOT NULL DEFAULT 0,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_group_members"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_group_members"."group_id" IS '节点分组 ID';
COMMENT ON COLUMN "public"."node_group_members"."client_ip" IS '客户端 IP 快照';
COMMENT ON COLUMN "public"."node_group_members"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."node_group_members"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_group_members"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_group_members"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_group_members" IS '执行节点分组成员表';


-- ----------------------------
-- Table structure for node_workflows
-- ----------------------------
CREATE TABLE "public"."node_workflows" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "automa_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "workflow_id" int8 NOT NULL DEFAULT 0,
  "expected_revision" int4 NOT NULL DEFAULT 0,
  "actual_revision" int4 NOT NULL DEFAULT 0,
  "content_hash" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "desired_present" bool NOT NULL DEFAULT true,
  "sync_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "last_sync_at" timestamptz(6),
  "last_check_at" timestamptz(6),
  "last_error" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_workflows"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_workflows"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."node_workflows"."client_ip" IS '客户端 IP 快照，用于区分同名执行节点';
COMMENT ON COLUMN "public"."node_workflows"."automa_id" IS 'Automa 原始工作流 ID';
COMMENT ON COLUMN "public"."node_workflows"."workflow_id" IS '服务端工作流主表 ID';
COMMENT ON COLUMN "public"."node_workflows"."expected_revision" IS '服务端期望节点安装的工作流版本';
COMMENT ON COLUMN "public"."node_workflows"."actual_revision" IS '节点实际上报的工作流版本';
COMMENT ON COLUMN "public"."node_workflows"."content_hash" IS '节点当前工作流内容 hash';
COMMENT ON COLUMN "public"."node_workflows"."desired_present" IS '是否期望该工作流存在于节点中';
COMMENT ON COLUMN "public"."node_workflows"."sync_status" IS '同步状态：pending、syncing、synced、failed、deleting、deleted';
COMMENT ON COLUMN "public"."node_workflows"."last_sync_at" IS '最近一次安装、更新或删除完成时间';
COMMENT ON COLUMN "public"."node_workflows"."last_check_at" IS '最近一次节点清单上报时间';
COMMENT ON COLUMN "public"."node_workflows"."last_error" IS '最近一次同步错误信息';
COMMENT ON COLUMN "public"."node_workflows"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_workflows"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_workflows"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_workflows" IS '执行节点工作流安装状态表';


-- ----------------------------
-- Table structure for node_packages
-- ----------------------------
CREATE TABLE "public"."node_packages" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "package_id" int8 NOT NULL DEFAULT 0,
  "expected_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "actual_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "expected_sha256" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "actual_sha256" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "desired_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'installed'::character varying,
  "install_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'unknown'::character varying,
  "last_install_at" timestamptz(6),
  "last_check_at" timestamptz(6),
  "last_error" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_packages"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_packages"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."node_packages"."client_ip" IS '客户端 IP 快照，用于区分同名执行节点';
COMMENT ON COLUMN "public"."node_packages"."package_id" IS '关联的 Automa 插件安装包 ID';
COMMENT ON COLUMN "public"."node_packages"."expected_version" IS '服务端期望安装的插件版本';
COMMENT ON COLUMN "public"."node_packages"."actual_version" IS '节点实际上报的插件版本';
COMMENT ON COLUMN "public"."node_packages"."expected_sha256" IS '服务端期望安装包 sha256';
COMMENT ON COLUMN "public"."node_packages"."actual_sha256" IS '节点实际上报的安装内容 sha256';
COMMENT ON COLUMN "public"."node_packages"."desired_status" IS '期望状态：installed 安装，removed 移除';
COMMENT ON COLUMN "public"."node_packages"."install_status" IS '安装状态：unknown、pending、installing、installed、failed、removed';
COMMENT ON COLUMN "public"."node_packages"."last_install_at" IS '最近一次安装或更新完成时间';
COMMENT ON COLUMN "public"."node_packages"."last_check_at" IS '最近一次节点上报检查时间';
COMMENT ON COLUMN "public"."node_packages"."last_error" IS '最近一次安装或检查错误';
COMMENT ON COLUMN "public"."node_packages"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_packages"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_packages"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_packages" IS '执行节点插件安装状态表';


-- ----------------------------
-- Table structure for node_commands
-- ----------------------------
CREATE TABLE "public"."node_commands" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "command_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "command_type" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "payload_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "result_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "error_message" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "retry_count" int4 NOT NULL DEFAULT 0,
  "timeout_seconds" int4 NOT NULL DEFAULT 60,
  "sent_at" timestamptz(6),
  "ack_at" timestamptz(6),
  "finished_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_commands"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_commands"."command_id" IS '服务端命令唯一 ID，用于客户端回调和幂等处理';
COMMENT ON COLUMN "public"."node_commands"."client_ip" IS '目标客户端 IP';
COMMENT ON COLUMN "public"."node_commands"."node_id" IS '目标执行节点 ID';
COMMENT ON COLUMN "public"."node_commands"."command_type" IS '命令类型：install_workflow、delete_workflow、sync_inventory、install_package、restart_node、execute_workflow 等';
COMMENT ON COLUMN "public"."node_commands"."status" IS '命令状态：pending、sent、running、success、failed、cancelled、timeout';
COMMENT ON COLUMN "public"."node_commands"."payload_json" IS '命令参数 JSON';
COMMENT ON COLUMN "public"."node_commands"."result_json" IS '命令执行结果 JSON';
COMMENT ON COLUMN "public"."node_commands"."error_message" IS '命令失败信息';
COMMENT ON COLUMN "public"."node_commands"."retry_count" IS '命令重试次数';
COMMENT ON COLUMN "public"."node_commands"."timeout_seconds" IS '命令超时时间，单位秒';
COMMENT ON COLUMN "public"."node_commands"."sent_at" IS '命令发送时间';
COMMENT ON COLUMN "public"."node_commands"."ack_at" IS '客户端确认收到时间';
COMMENT ON COLUMN "public"."node_commands"."finished_at" IS '命令完成时间';
COMMENT ON COLUMN "public"."node_commands"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_commands"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_commands"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_commands" IS '执行节点命令表';


-- ----------------------------
-- Table structure for node_events
-- ----------------------------
CREATE TABLE "public"."node_events" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
  ),
  "node_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "event_type" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "level" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'info'::character varying,
  "message" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "payload_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."node_events"."id" IS '自增 ID';
COMMENT ON COLUMN "public"."node_events"."node_id" IS '执行节点 ID';
COMMENT ON COLUMN "public"."node_events"."client_ip" IS '客户端 IP 快照';
COMMENT ON COLUMN "public"."node_events"."event_type" IS '事件类型：register、heartbeat、disconnect、command、workflow_sync、package_install、error 等';
COMMENT ON COLUMN "public"."node_events"."level" IS '事件级别：debug、info、warn、error';
COMMENT ON COLUMN "public"."node_events"."message" IS '可读事件消息';
COMMENT ON COLUMN "public"."node_events"."payload_json" IS '事件扩展数据 JSON';
COMMENT ON COLUMN "public"."node_events"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."node_events"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."node_events"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."node_events" IS '执行节点事件日志表';


-- ----------------------------
-- Primary keys
-- ----------------------------
ALTER TABLE "public"."automa_workflows" ADD CONSTRAINT "automa_workflows_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."clients" ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."automa_packages" ADD CONSTRAINT "automa_packages_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."task_records" ADD CONSTRAINT "task_records_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."task_record_files" ADD CONSTRAINT "task_record_files_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."task_queue" ADD CONSTRAINT "task_queue_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."task_attempts" ADD CONSTRAINT "task_attempts_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_groups" ADD CONSTRAINT "node_groups_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_group_members" ADD CONSTRAINT "node_group_members_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_workflows" ADD CONSTRAINT "node_workflows_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_packages" ADD CONSTRAINT "node_packages_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_commands" ADD CONSTRAINT "node_commands_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."node_events" ADD CONSTRAINT "node_events_pkey" PRIMARY KEY ("id");


-- ----------------------------
-- Indexes for automa_workflows
-- ----------------------------
CREATE UNIQUE INDEX "idx_automa_workflows_automa_id" ON "public"."automa_workflows" USING btree (
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_automa_workflows_source_node_id" ON "public"."automa_workflows" USING btree (
  "source_node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_automa_workflows_updated_at" ON "public"."automa_workflows" USING btree (
  "updated_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;

-- ----------------------------
-- Indexes for clients
-- ----------------------------
CREATE INDEX "idx_clients_client_ip" ON "public"."clients" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX "idx_clients_node_id" ON "public"."clients" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND client_ip <> ''::text AND node_id <> ''::text;
CREATE INDEX "idx_clients_status_last_seen" ON "public"."clients" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "last_seen_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_clients_busy_status" ON "public"."clients" USING btree (
  "busy_status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_clients_current_execution_id" ON "public"."clients" USING btree (
  "current_execution_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND current_execution_id <> ''::text;


-- ----------------------------
-- Indexes for automa_packages
-- ----------------------------
CREATE INDEX "idx_automa_packages_status" ON "public"."automa_packages" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX "idx_automa_packages_version_sha256" ON "public"."automa_packages" USING btree (
  "version" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "sha256" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND version <> ''::text AND sha256 <> ''::text;


-- ----------------------------
-- Indexes for tasks
-- ----------------------------
CREATE INDEX "idx_tasks_automa_id" ON "public"."tasks" USING btree (
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_client_ip" ON "public"."tasks" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_node_id" ON "public"."tasks" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_target_group_id" ON "public"."tasks" USING btree (
  "target_group_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND target_group_id > 0;
CREATE INDEX "idx_tasks_enabled_cron" ON "public"."tasks" USING btree (
  "enabled" "pg_catalog"."bool_ops" ASC NULLS LAST,
  "cron_expression" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_updated_at" ON "public"."tasks" USING btree (
  "updated_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for task_records
-- ----------------------------
CREATE INDEX "idx_task_records_client_ip" ON "public"."task_records" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_node_id" ON "public"."task_records" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_execution_id" ON "public"."task_records" USING btree (
  "execution_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_command_id" ON "public"."task_records" USING btree (
  "command_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND command_id <> ''::text;
CREATE INDEX "idx_task_records_automa_execution_id" ON "public"."task_records" USING btree (
  "automa_execution_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_queue_id" ON "public"."task_records" USING btree (
  "queue_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND queue_id > 0;
CREATE INDEX "idx_task_records_created_at" ON "public"."task_records" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_status_started_at" ON "public"."task_records" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "started_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_task_id" ON "public"."task_records" USING btree (
  "task_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_workflow_id" ON "public"."task_records" USING btree (
  "workflow_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for task_record_files
-- ----------------------------
CREATE INDEX "idx_task_record_files_record_id" ON "public"."task_record_files" USING btree (
  "record_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_record_files_task_id" ON "public"."task_record_files" USING btree (
  "task_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_record_files_node_id" ON "public"."task_record_files" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_record_files_execution_id" ON "public"."task_record_files" USING btree (
  "execution_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for task_queue
-- ----------------------------
CREATE INDEX "idx_task_queue_status_scheduled" ON "public"."task_queue" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "scheduled_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST,
  "priority" "pg_catalog"."int4_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_queue_task_id" ON "public"."task_queue" USING btree (
  "task_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_queue_node_id" ON "public"."task_queue" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_queue_target_group_id" ON "public"."task_queue" USING btree (
  "target_group_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND target_group_id > 0;


-- ----------------------------
-- Indexes for task_attempts
-- ----------------------------
CREATE INDEX "idx_task_attempts_queue_id" ON "public"."task_attempts" USING btree (
  "queue_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_attempts_record_id" ON "public"."task_attempts" USING btree (
  "record_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_attempts_node_status" ON "public"."task_attempts" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_attempts_execution_id" ON "public"."task_attempts" USING btree (
  "execution_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND execution_id <> ''::text;


-- ----------------------------
-- Indexes for node_groups
-- ----------------------------
CREATE UNIQUE INDEX "idx_node_groups_group_name" ON "public"."node_groups" USING btree (
  "group_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND group_name <> ''::text;
CREATE INDEX "idx_node_groups_enabled" ON "public"."node_groups" USING btree (
  "enabled" "pg_catalog"."bool_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for node_group_members
-- ----------------------------
CREATE UNIQUE INDEX "idx_node_group_members_group_node" ON "public"."node_group_members" USING btree (
  "group_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND group_id > 0 AND client_ip <> ''::text AND node_id <> ''::text;
CREATE INDEX "idx_node_group_members_node_id" ON "public"."node_group_members" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for node_workflows
-- ----------------------------
CREATE UNIQUE INDEX "idx_node_workflows_node_automa" ON "public"."node_workflows" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND client_ip <> ''::text AND node_id <> ''::text AND automa_id <> ''::text;
CREATE INDEX "idx_node_workflows_client_ip" ON "public"."node_workflows" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_workflows_automa_id" ON "public"."node_workflows" USING btree (
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_workflows_node_status" ON "public"."node_workflows" USING btree (
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "sync_status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for node_packages
-- ----------------------------
CREATE UNIQUE INDEX "idx_node_packages_node_package" ON "public"."node_packages" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "package_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND client_ip <> ''::text AND node_id <> ''::text AND package_id > 0;
CREATE INDEX "idx_node_packages_client_ip" ON "public"."node_packages" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_packages_install_status" ON "public"."node_packages" USING btree (
  "install_status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for node_commands
-- ----------------------------
CREATE UNIQUE INDEX "idx_node_commands_command_id" ON "public"."node_commands" USING btree (
  "command_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL AND command_id <> ''::text;
CREATE INDEX "idx_node_commands_node_status" ON "public"."node_commands" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_commands_created_at" ON "public"."node_commands" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;


-- ----------------------------
-- Indexes for node_events
-- ----------------------------
CREATE INDEX "idx_node_events_node_created_at" ON "public"."node_events" USING btree (
  "node_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "created_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_events_client_created_at" ON "public"."node_events" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "created_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_node_events_event_type" ON "public"."node_events" USING btree (
  "event_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
