/*
 Navicat Premium Dump SQL

 Source Server         : 192.168.19.104
 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Host           : 192.168.19.104:5432
 Source Catalog        : browserflow
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 22/05/2026 15:37:15
*/


-- ----------------------------
-- Sequence structure for automa_workflows_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."automa_workflows_id_seq";
CREATE SEQUENCE "public"."automa_workflows_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for clients_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."clients_id_seq";
CREATE SEQUENCE "public"."clients_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for task_records_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."task_records_id_seq";
CREATE SEQUENCE "public"."task_records_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for tasks_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tasks_id_seq";
CREATE SEQUENCE "public"."tasks_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for automa_workflows
-- ----------------------------
DROP TABLE IF EXISTS "public"."automa_workflows";
CREATE TABLE "public"."automa_workflows" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "automa_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "name" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "description" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "source" int4 NOT NULL DEFAULT 1,
  "source_ip" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "source_user_agent" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "automa_version" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "ext_version" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "created_at_automa" int8 NOT NULL DEFAULT 0,
  "updated_at_automa" int8 NOT NULL DEFAULT 0,
  "is_disabled" bool NOT NULL DEFAULT false,
  "is_protected" bool NOT NULL DEFAULT false,
  "node_count" int4 NOT NULL DEFAULT 0,
  "edge_count" int4 NOT NULL DEFAULT 0,
  "raw_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "normalized_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "content_hash" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "revision" int4 NOT NULL DEFAULT 1,
  "first_synced_at" timestamptz(6),
  "last_synced_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamp(6),
  "automa_name" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "automa_description" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text
)
;
COMMENT ON COLUMN "public"."automa_workflows"."id" IS '后端自增主键';
COMMENT ON COLUMN "public"."automa_workflows"."automa_id" IS 'Automa 原始工作流 ID，判断同一个工作流的唯一依据';
COMMENT ON COLUMN "public"."automa_workflows"."name" IS '工作流名称，默认从 Automa 导出的 JSON 中解析';
COMMENT ON COLUMN "public"."automa_workflows"."description" IS '工作流描述，默认从 Automa 导出的 JSON 中解析';
COMMENT ON COLUMN "public"."automa_workflows"."source" IS '来源：1页面导入 2客户端同步 默认1';
COMMENT ON COLUMN "public"."automa_workflows"."source_ip" IS '最后同步来源 IP';
COMMENT ON COLUMN "public"."automa_workflows"."source_user_agent" IS '最后同步来源浏览器 User-Agent';
COMMENT ON COLUMN "public"."automa_workflows"."automa_version" IS '工作流保存时的 Automa 插件版本';
COMMENT ON COLUMN "public"."automa_workflows"."ext_version" IS 'Automa 导出文件中的 extVersion';
COMMENT ON COLUMN "public"."automa_workflows"."created_at_automa" IS 'Automa 原始 createdAt，通常为毫秒时间戳';
COMMENT ON COLUMN "public"."automa_workflows"."updated_at_automa" IS 'Automa 原始 updatedAt，通常为毫秒时间戳';
COMMENT ON COLUMN "public"."automa_workflows"."is_disabled" IS '是否被 Automa 禁用 默认false';
COMMENT ON COLUMN "public"."automa_workflows"."is_protected" IS '是否受保护 true客户端不能同步 false客户端可同步 默认false';
COMMENT ON COLUMN "public"."automa_workflows"."node_count" IS '工作流节点数量';
COMMENT ON COLUMN "public"."automa_workflows"."edge_count" IS '工作流连线数量';
COMMENT ON COLUMN "public"."automa_workflows"."raw_json" IS 'Automa 导出的原始完整 JSON 数据';
COMMENT ON COLUMN "public"."automa_workflows"."normalized_json" IS '规范化后的工作流 JSON，用于计算 content_hash 或内容对比';
COMMENT ON COLUMN "public"."automa_workflows"."content_hash" IS '核心内容 hash，用于判断工作流内容是否变化';
COMMENT ON COLUMN "public"."automa_workflows"."revision" IS '当前版本号，每次内容变化时加 1';
COMMENT ON COLUMN "public"."automa_workflows"."first_synced_at" IS '第一次同步到后端的时间';
COMMENT ON COLUMN "public"."automa_workflows"."last_synced_at" IS '最近一次同步到后端的时间';
COMMENT ON COLUMN "public"."automa_workflows"."created_at" IS '后端记录创建时间';
COMMENT ON COLUMN "public"."automa_workflows"."updated_at" IS '后端记录更新时间';
COMMENT ON COLUMN "public"."automa_workflows"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "public"."automa_workflows"."automa_name" IS 'Automa 工作流 JSON 中的原始名称';
COMMENT ON COLUMN "public"."automa_workflows"."automa_description" IS 'Automa 工作流 JSON 中的原始描述';
COMMENT ON TABLE "public"."automa_workflows" IS '工作流表';

-- ----------------------------
-- Table structure for clients
-- ----------------------------
DROP TABLE IF EXISTS "public"."clients";
CREATE TABLE "public"."clients" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "client_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "user_agent" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'offline'::character varying,
  "plugin_status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'unknown'::character varying,
  "automa_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "browser_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "browser_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "os_name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "os_version" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "hostname" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "is_banned" bool NOT NULL DEFAULT false,
  "ban_reason" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "first_seen_at" timestamptz(6) NOT NULL DEFAULT now(),
  "last_seen_at" timestamptz(6) NOT NULL DEFAULT now(),
  "connected_at" timestamptz(6),
  "disconnected_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."clients"."id" IS '主键 ID，自增';
COMMENT ON COLUMN "public"."clients"."client_id" IS '客户端唯一标识（建议前端生成 UUID 并存储在 localStorage，用于唯一识别一个浏览器实例）';
COMMENT ON COLUMN "public"."clients"."client_name" IS '客户端名称（可自定义，例如：办公室电脑、家用电脑）';
COMMENT ON COLUMN "public"."clients"."client_ip" IS '客户端当前或最后一次连接 IP';
COMMENT ON COLUMN "public"."clients"."user_agent" IS '客户端浏览器 User-Agent 字符串';
COMMENT ON COLUMN "public"."clients"."status" IS '客户端当前状态：online 在线，offline 离线';
COMMENT ON COLUMN "public"."clients"."plugin_status" IS 'Automa 插件状态：unknown 未知，installed 已安装，not_installed 未安装，disabled 已禁用，error 异常';
COMMENT ON COLUMN "public"."clients"."automa_version" IS 'Automa 插件版本号';
COMMENT ON COLUMN "public"."clients"."browser_name" IS '浏览器名称，例如 Chrome、Edge';
COMMENT ON COLUMN "public"."clients"."browser_version" IS '浏览器版本号';
COMMENT ON COLUMN "public"."clients"."os_name" IS '操作系统名称，例如 Windows、macOS、Linux';
COMMENT ON COLUMN "public"."clients"."os_version" IS '操作系统版本号';
COMMENT ON COLUMN "public"."clients"."hostname" IS '客户端设备主机名';
COMMENT ON COLUMN "public"."clients"."is_banned" IS '是否被拉黑（true 表示该客户端被禁止使用）';
COMMENT ON COLUMN "public"."clients"."ban_reason" IS '客户端被拉黑的原因';
COMMENT ON COLUMN "public"."clients"."first_seen_at" IS '客户端第一次连接到服务端的时间（注册时间）';
COMMENT ON COLUMN "public"."clients"."last_seen_at" IS '客户端最近一次心跳或交互时间（用于判断是否在线）';
COMMENT ON COLUMN "public"."clients"."connected_at" IS '最近一次建立 WebSocket 连接的时间';
COMMENT ON COLUMN "public"."clients"."disconnected_at" IS '最近一次断开 WebSocket 连接的时间';
COMMENT ON COLUMN "public"."clients"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."clients"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."clients"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."clients" IS '客户端记录表';

-- ----------------------------
-- Table structure for task_records
-- ----------------------------
DROP TABLE IF EXISTS "public"."task_records";
CREATE TABLE "public"."task_records" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "task_id" int8 NOT NULL DEFAULT 0,
  "workflow_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL,
  "client_ip" varchar(64) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "trigger_type" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'manual'::character varying,
  "status" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "result_json" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "error_message" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "started_at" timestamptz(6),
  "finished_at" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."task_records"."id" IS '自增ID';
COMMENT ON COLUMN "public"."task_records"."task_id" IS '关联的任务配置ID';
COMMENT ON COLUMN "public"."task_records"."workflow_id" IS '执行时使用的 Automa 工作流 ID';
COMMENT ON COLUMN "public"."task_records"."client_ip" IS '执行目标客户端 IP';
COMMENT ON COLUMN "public"."task_records"."trigger_type" IS '触发类型：manual 手动触发，cron 定时触发，task_create 创建任务触发，skill Skill触发，system 系统触发';
COMMENT ON COLUMN "public"."task_records"."status" IS '执行状态：pending、queued、running、success、failed、cancelled';
COMMENT ON COLUMN "public"."task_records"."params_json" IS '本次执行使用的参数快照';
COMMENT ON COLUMN "public"."task_records"."result_json" IS '本次执行结果内容';
COMMENT ON COLUMN "public"."task_records"."error_message" IS '执行失败时的错误信息';
COMMENT ON COLUMN "public"."task_records"."started_at" IS '开始执行时间';
COMMENT ON COLUMN "public"."task_records"."finished_at" IS '执行结束时间';
COMMENT ON COLUMN "public"."task_records"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "public"."task_records"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "public"."task_records"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."task_records" IS '任务执行记录表';

-- ----------------------------
-- Table structure for tasks
-- ----------------------------
DROP TABLE IF EXISTS "public"."tasks";
CREATE TABLE "public"."tasks" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "description" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "automa_id" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "client_ip" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "cron_expression" varchar(120) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "enabled" bool NOT NULL DEFAULT true,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "deleted_at" timestamptz(6)
)
;
COMMENT ON COLUMN "public"."tasks"."id" IS '自增ID';
COMMENT ON COLUMN "public"."tasks"."name" IS '任务名称';
COMMENT ON COLUMN "public"."tasks"."description" IS '任务说明';
COMMENT ON COLUMN "public"."tasks"."automa_id" IS 'Automa 原始工作流 ID';
COMMENT ON COLUMN "public"."tasks"."client_ip" IS '目标客户端 IP，为空则随机匹配在线且拥有此工作流的客户端执行';
COMMENT ON COLUMN "public"."tasks"."cron_expression" IS 'Cron 表达式，为空表示立即执行';
COMMENT ON COLUMN "public"."tasks"."params_json" IS '任务自定义参数，key/value 格式，使用 JSONB 存储';
COMMENT ON COLUMN "public"."tasks"."enabled" IS '是否启用';
COMMENT ON COLUMN "public"."tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "public"."tasks"."updated_at" IS '更新时间';
COMMENT ON COLUMN "public"."tasks"."deleted_at" IS '软删除时间';
COMMENT ON TABLE "public"."tasks" IS '任务配置表';

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."automa_workflows_id_seq"
OWNED BY "public"."automa_workflows"."id";
SELECT setval('"public"."automa_workflows_id_seq"', 6, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."clients_id_seq"
OWNED BY "public"."clients"."id";
SELECT setval('"public"."clients_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."task_records_id_seq"
OWNED BY "public"."task_records"."id";
SELECT setval('"public"."task_records_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."tasks_id_seq"
OWNED BY "public"."tasks"."id";
SELECT setval('"public"."tasks_id_seq"', 2, true);

-- ----------------------------
-- Indexes structure for table automa_workflows
-- ----------------------------
CREATE UNIQUE INDEX "idx_automa_workflows_automa_id" ON "public"."automa_workflows" USING btree (
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;

-- ----------------------------
-- Primary Key structure for table automa_workflows
-- ----------------------------
ALTER TABLE "public"."automa_workflows" ADD CONSTRAINT "automa_workflows_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table clients
-- ----------------------------
CREATE INDEX "idx_clients_client_id" ON "public"."clients" USING btree (
  "client_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_clients_client_ip" ON "public"."clients" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;

-- ----------------------------
-- Primary Key structure for table clients
-- ----------------------------
ALTER TABLE "public"."clients" ADD CONSTRAINT "automa_clients_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table task_records
-- ----------------------------
CREATE INDEX "idx_task_records_client_ip" ON "public"."task_records" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_created_at" ON "public"."task_records" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_status_started_at" ON "public"."task_records" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "started_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_task_id" ON "public"."task_records" USING btree (
  "task_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_task_records_workflow_id" ON "public"."task_records" USING btree (
  "workflow_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;

-- ----------------------------
-- Primary Key structure for table task_records
-- ----------------------------
ALTER TABLE "public"."task_records" ADD CONSTRAINT "task_records_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table tasks
-- ----------------------------
CREATE INDEX "idx_tasks_automa_id" ON "public"."tasks" USING btree (
  "automa_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_client_ip" ON "public"."tasks" USING btree (
  "client_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_enabled_cron" ON "public"."tasks" USING btree (
  "enabled" "pg_catalog"."bool_ops" ASC NULLS LAST,
  "cron_expression" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE deleted_at IS NULL;
CREATE INDEX "idx_tasks_updated_at" ON "public"."tasks" USING btree (
  "updated_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
) WHERE deleted_at IS NULL;

-- ----------------------------
-- Primary Key structure for table tasks
-- ----------------------------
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");
