// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package agents

// ControllerV1 agents controller 执行端控制器
type ControllerV1 struct{}

// NewV1 creates agents controller 创建执行端控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
