// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package workflows

// ControllerV1 workflows controller 工作流控制器
type ControllerV1 struct{}

// NewV1 creates workflows controller 创建工作流控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
