// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package taskdata

import (
	"context"
	"encoding/json"
	"strings"

	"github.com/Zany2/browserflow/backend/internal/dao"
	"github.com/Zany2/browserflow/backend/internal/model"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/os/gtime"
	"github.com/gogf/gf/v2/util/gconv"
)

// buildTaskMap enriches task table data for frontend display 补充前端展示字段
func BuildTaskMap(ctx context.Context, record gdb.Record) (*model.TaskResModel, error) {
	if record.IsEmpty() {
		return nil, nil
	}

	columns := dao.Tasks.Columns()
	workflowID := strings.TrimSpace(gconv.String(record[columns.AutomaId]))
	clientIP := strings.TrimSpace(gconv.String(record[columns.ClientIp]))
	params, err := decodeJSONMap(strings.TrimSpace(gconv.String(record[columns.ParamsJson])))
	if err != nil {
		return nil, err
	}

	workflowName := ""
	if workflowID != "" {
		workflowColumns := dao.AutomaWorkflows.Columns()
		workflowRecord, err := dao.AutomaWorkflows.Ctx(ctx).Where(workflowColumns.AutomaId, workflowID).One()
		if err != nil {
			return nil, err
		}
		if !workflowRecord.IsEmpty() {
			workflowName = strings.TrimSpace(gconv.String(workflowRecord[workflowColumns.Name]))
		}
	}

	clientID := ""
	clientName := ""
	if clientIP != "" {
		clientColumns := dao.Clients.Columns()
		clientRecord, err := dao.Clients.Ctx(ctx).Where(clientColumns.ClientIp, clientIP).One()
		if err != nil {
			return nil, err
		}
		if !clientRecord.IsEmpty() {
			clientID = strings.TrimSpace(gconv.String(clientRecord[clientColumns.ClientId]))
			clientName = strings.TrimSpace(gconv.String(clientRecord[clientColumns.ClientName]))
		}
	}

	return &model.TaskResModel{
		ID:             gconv.Int64(record[columns.Id]),
		Name:           strings.TrimSpace(gconv.String(record[columns.Name])),
		Description:    strings.TrimSpace(gconv.String(record[columns.Description])),
		AutomaID:       workflowID,
		WorkflowID:     workflowID,
		WorkflowName:   workflowName,
		ClientID:       clientID,
		ClientName:     clientName,
		ClientIP:       clientIP,
		CronExpression: strings.TrimSpace(gconv.String(record[columns.CronExpression])),
		Params:         params,
		Enabled:        gconv.Bool(record[columns.Enabled]),
		CreatedAt:      recordTime(record[columns.CreatedAt]),
		UpdatedAt:      recordTime(record[columns.UpdatedAt]),
		DeletedAt:      recordTime(record[columns.DeletedAt]),
	}, nil
}

// buildTaskRecordMap enriches execution record data for frontend display 补充执行记录展示字段
func BuildTaskRecordMap(ctx context.Context, record gdb.Record) (*model.TaskRecordResModel, error) {
	if record.IsEmpty() {
		return nil, nil
	}

	columns := dao.TaskRecords.Columns()
	taskID := gconv.Int64(record[columns.TaskId])
	workflowID := strings.TrimSpace(gconv.String(record[columns.WorkflowId]))
	clientIP := strings.TrimSpace(gconv.String(record[columns.ClientIp]))
	params, err := decodeJSONMap(strings.TrimSpace(gconv.String(record[columns.ParamsJson])))
	if err != nil {
		return nil, err
	}
	result := model.JSONMap{}
	if resultJSON := strings.TrimSpace(gconv.String(record[columns.ResultJson])); resultJSON != "" {
		if err := json.Unmarshal([]byte(resultJSON), &result); err != nil {
			rawResult, _ := json.Marshal(resultJSON)
			result = model.JSONMap{"raw": rawResult}
		}
	}

	taskName := ""
	if taskID > 0 {
		taskColumns := dao.Tasks.Columns()
		taskRecord, err := dao.Tasks.Ctx(ctx).WherePri(taskID).One()
		if err != nil {
			return nil, err
		}
		if !taskRecord.IsEmpty() {
			taskName = strings.TrimSpace(gconv.String(taskRecord[taskColumns.Name]))
		}
	}

	workflowName := ""
	if workflowID != "" {
		workflowColumns := dao.AutomaWorkflows.Columns()
		workflowRecord, err := dao.AutomaWorkflows.Ctx(ctx).Where(workflowColumns.AutomaId, workflowID).One()
		if err != nil {
			return nil, err
		}
		if !workflowRecord.IsEmpty() {
			workflowName = strings.TrimSpace(gconv.String(workflowRecord[workflowColumns.Name]))
		}
	}

	clientID := ""
	clientName := ""
	if clientIP != "" {
		clientColumns := dao.Clients.Columns()
		clientRecord, err := dao.Clients.Ctx(ctx).Where(clientColumns.ClientIp, clientIP).One()
		if err != nil {
			return nil, err
		}
		if !clientRecord.IsEmpty() {
			clientID = strings.TrimSpace(gconv.String(clientRecord[clientColumns.ClientId]))
			clientName = strings.TrimSpace(gconv.String(clientRecord[clientColumns.ClientName]))
		}
	}

	return &model.TaskRecordResModel{
		ID:           gconv.Int64(record[columns.Id]),
		TaskID:       taskID,
		TaskName:     taskName,
		WorkflowID:   workflowID,
		WorkflowName: workflowName,
		ClientID:     clientID,
		ClientName:   clientName,
		ClientIP:     clientIP,
		TriggerType:  strings.TrimSpace(gconv.String(record[columns.TriggerType])),
		Status:       strings.TrimSpace(gconv.String(record[columns.Status])),
		Params:       params,
		Result:       result,
		ErrorMessage: strings.TrimSpace(gconv.String(record[columns.ErrorMessage])),
		StartedAt:    recordTime(record[columns.StartedAt]),
		FinishedAt:   recordTime(record[columns.FinishedAt]),
		CreatedAt:    recordTime(record[columns.CreatedAt]),
		UpdatedAt:    recordTime(record[columns.UpdatedAt]),
		DeletedAt:    recordTime(record[columns.DeletedAt]),
	}, nil
}

// resolveClientIP finds executable client ip from request data 按请求数据解析可执行客户端 IP
func ResolveClientIP(ctx context.Context, clientID string, clientIP string) (string, error) {
	clientID = strings.TrimSpace(clientID)
	clientIP = strings.TrimSpace(clientIP)
	columns := dao.Clients.Columns()

	if clientIP != "" {
		return clientIP, nil
	}
	if clientID == "" {
		return "", nil
	}

	record, err := dao.Clients.Ctx(ctx).
		Where(columns.ClientId, clientID).
		One()
	if err != nil || !record.IsEmpty() {
		return strings.TrimSpace(gconv.String(record[columns.ClientIp])), err
	}

	record, err = dao.Clients.Ctx(ctx).
		WherePri(gconv.Int64(clientID)).
		One()
	if err != nil || record.IsEmpty() {
		return "", err
	}
	return strings.TrimSpace(gconv.String(record[columns.ClientIp])), nil
}

// decodeJSONMap parses json object text for API models 解析 JSON 对象文本
func decodeJSONMap(value string) (model.JSONMap, error) {
	result := model.JSONMap{}
	if value == "" {
		return result, nil
	}
	if err := json.Unmarshal([]byte(value), &result); err != nil {
		return nil, err
	}
	return result, nil
}

// encodeJSONMap serializes map fields for jsonb columns 序列化 JSONB 字段
func EncodeJSONMap(value model.JSONMap) (string, error) {
	if value == nil {
		return "{}", nil
	}
	body, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return string(body), nil
}

// recordTime converts database time values to GoFrame time 转换数据库时间字段
func recordTime(value any) *gtime.Time {
	if value == nil {
		return nil
	}
	t := gconv.Time(value)
	if t.IsZero() {
		return nil
	}
	return gtime.NewFromTime(t)
}

// FindWorkflowIDsByName finds workflow ids by fuzzy name. ????????????? ID?
func FindWorkflowIDsByName(ctx context.Context, workflowName string) ([]string, error) {
	columns := dao.AutomaWorkflows.Columns()
	records, err := dao.AutomaWorkflows.Ctx(ctx).
		Fields(columns.AutomaId).
		Where(columns.Name+" LIKE ?", "%"+workflowName+"%").
		All()
	if err != nil {
		return nil, err
	}

	workflowIDs := make([]string, 0, len(records))
	for _, record := range records {
		workflowID := strings.TrimSpace(gconv.String(record[columns.AutomaId]))
		if workflowID != "" {
			workflowIDs = append(workflowIDs, workflowID)
		}
	}
	return workflowIDs, nil
}

// NormalizeTriggerType keeps execution records in known trigger types. ???????????
func NormalizeTriggerType(triggerType string) string {
	triggerType = strings.TrimSpace(triggerType)
	switch triggerType {
	case "cron", "task_create", "skill", "system":
		return triggerType
	default:
		return "manual"
	}
}
