// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package clientops

import (
	"context"
	"strings"

	"github.com/Zany2/browserflow/backend/internal/dao"
	"github.com/Zany2/browserflow/backend/internal/model"
	"github.com/Zany2/browserflow/backend/internal/model/entity"
	websockets "github.com/Zany2/browserflow/backend/utility/websocket"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
)

// QueryRecord queries a client by node id, client ip, or primary id.
func QueryRecord(ctx context.Context, id string) (gdb.Record, error) {
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, nil
	}

	columns := dao.Clients.Columns()
	record, err := dao.Clients.Ctx(ctx).Where(columns.NodeId, id).One()
	if err != nil || !record.IsEmpty() {
		return record, err
	}

	record, err = dao.Clients.Ctx(ctx).Where(columns.ClientIp, id).One()
	if err != nil || !record.IsEmpty() {
		return record, err
	}

	primaryID := gconv.Int64(id)
	if primaryID <= 0 {
		return record, nil
	}
	return dao.Clients.Ctx(ctx).WherePri(primaryID).One()
}

// ScopedModel scopes updates to one client node. 优先按节点限定单个客户端
func ScopedModel(ctx context.Context, record gdb.Record) *gdb.Model {
	columns := dao.Clients.Columns()
	model := dao.Clients.Ctx(ctx)
	if record.IsEmpty() {
		return model.Where(columns.Id, 0)
	}
	if nodeID := NodeIDFromRecord(record); nodeID != "" {
		return model.Where(columns.NodeId, nodeID)
	}
	if primaryID := gconv.Int64(record[columns.Id]); primaryID > 0 {
		return model.WherePri(primaryID)
	}
	return model.Where(columns.ClientIp, ClientIPFromRecord(record))
}

// TargetConnectionID returns websocket identity for one client node.
func TargetConnectionID(record gdb.Record) string {
	if nodeID := NodeIDFromRecord(record); nodeID != "" {
		return nodeID
	}
	return ClientIPFromRecord(record)
}

// ClientIPFromRecord returns display client ip.
func ClientIPFromRecord(record gdb.Record) string {
	if record.IsEmpty() {
		return ""
	}
	return strings.TrimSpace(gconv.String(record[dao.Clients.Columns().ClientIp]))
}

// ClientIDFromRecord returns legacy client id.
func ClientIDFromRecord(record gdb.Record) string {
	if record.IsEmpty() {
		return ""
	}
	return strings.TrimSpace(gconv.String(record[dao.Clients.Columns().ClientId]))
}

// NodeIDFromRecord returns execution node id.
func NodeIDFromRecord(record gdb.Record) string {
	if record.IsEmpty() {
		return ""
	}
	return strings.TrimSpace(gconv.String(record[dao.Clients.Columns().NodeId]))
}

// RecordToEntity converts a database record to API detail model.
func RecordToEntity(record gdb.Record) (*entity.Clients, error) {
	if record.IsEmpty() {
		return nil, nil
	}
	client := &entity.Clients{}
	if err := gconv.Struct(record, client); err != nil {
		return nil, err
	}
	return client, nil
}

// QueryBannedRecord queries ban state by request ip.
func QueryBannedRecord(ctx context.Context, clientIP string) (gdb.Record, error) {
	clientIP = strings.TrimSpace(clientIP)
	if clientIP == "" {
		return nil, nil
	}
	columns := dao.Clients.Columns()
	return dao.Clients.Ctx(ctx).
		Where(columns.ClientIp, clientIP).
		Where(columns.IsBanned, true).
		One()
}

// RequestIP reads real client ip from request.
func RequestIP(ctx context.Context) string {
	request := g.RequestFromCtx(ctx)
	if request == nil {
		return ""
	}
	return strings.TrimSpace(request.GetClientIp())
}

// NotifyBanned tells connected node to stop reconnecting.
func NotifyBanned(ctx context.Context, connectionID string, clientIP string, nodeID string, clientID string, reason string) int {
	connectionID = strings.TrimSpace(connectionID)
	clientIP = strings.TrimSpace(clientIP)
	nodeID = strings.TrimSpace(nodeID)
	if connectionID == "" {
		return 0
	}

	websockets.Init(ctx)
	return websockets.SendNodeMessage(nodeID, clientIP, &model.WSResponse{
		Type:     model.WSMessageTypeClientBanned,
		ClientID: strings.TrimSpace(clientID),
		ClientIP: clientIP,
		NodeID:   nodeID,
		Message:  "客户端已被拉黑，将持续检测，解除拉黑后自动重连",
		Error:    strings.TrimSpace(reason),
		Data: map[string]any{
			"no_reconnect": true,
			"reason":       strings.TrimSpace(reason),
		},
	})
}

// CloseConnection closes current websocket connection.
func CloseConnection(ctx context.Context, connectionID string) int {
	connectionID = strings.TrimSpace(connectionID)
	if connectionID == "" {
		return 0
	}

	websockets.Init(ctx)
	return websockets.WsManage.CloseClientConnections(connectionID)
}
