// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package clientops

import (
	"context"
	"strings"

	"github.com/Zany2/browserflow/backend/internal/dao"
	"github.com/Zany2/browserflow/backend/internal/model"
	"github.com/Zany2/browserflow/backend/internal/model/entity"
	websockets "github.com/Zany2/browserflow/backend/utility/websocket"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
)

// queryClientRecord queries client by client ip or primary id 按客户端 IP 或主键查询客户端
func QueryRecord(ctx context.Context, id string) (gdb.Record, error) {
	// Normalize query id 规范化查询标识
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, nil
	}

	// Query by client ip first 优先按客户端 IP 查询
	columns := dao.Clients.Columns()
	record, err := dao.Clients.Ctx(ctx).
		Where(columns.ClientIp, id).
		One()
	if err != nil || !record.IsEmpty() {
		return record, err
	}

	// Query by primary id when numeric 数字标识再按主键查询
	primaryID := gconv.Int64(id)
	if primaryID <= 0 {
		return record, nil
	}
	return dao.Clients.Ctx(ctx).WherePri(primaryID).One()
}

// clientRecordToEntity converts a database record to API detail model 数据记录转换为客户端详情模型
func RecordToEntity(record gdb.Record) (*entity.Clients, error) {
	if record.IsEmpty() {
		return nil, nil
	}
	client := &entity.Clients{}
	if err := gconv.Struct(record, client); err != nil {
		return nil, err
	}
	return client, nil
}

// queryBannedClientRecord queries ban state by request ip 按请求 IP 查询拉黑状态
func QueryBannedRecord(ctx context.Context, clientIP string) (gdb.Record, error) {
	// Normalize input 规范化查询条件
	clientIP = strings.TrimSpace(clientIP)
	columns := dao.Clients.Columns()

	// Query by client ip 按当前请求 IP 检查
	if clientIP == "" {
		return nil, nil
	}
	return dao.Clients.Ctx(ctx).
		Where(columns.ClientIp, clientIP).
		Where(columns.IsBanned, true).
		One()
}

// getRequestClientIP reads real client ip from request 从请求中读取客户端 IP
func RequestIP(ctx context.Context) string {
	request := g.RequestFromCtx(ctx)
	if request == nil {
		return ""
	}
	return strings.TrimSpace(request.GetClientIp())
}

// notifyClientBanned tells connected client to stop reconnecting 通知已连接客户端停止重连
func NotifyBanned(ctx context.Context, clientIP string, clientID string, reason string) int {
	clientIP = strings.TrimSpace(clientIP)
	if clientIP == "" {
		return 0
	}

	// Ensure websocket manager exists 确保 WebSocket 管理器已初始化
	websockets.Init(ctx)
	return websockets.SendClientMessage(clientIP, &model.WSResponse{
		Type:     model.WSMessageTypeClientBanned,
		ClientID: strings.TrimSpace(clientID),
		ClientIP: clientIP,
		Message:  "客户端已被拉黑，将持续检测，解除拉黑后自动重连",
		Error:    strings.TrimSpace(reason),
		Data: g.Map{
			"no_reconnect": true,
			"reason":       strings.TrimSpace(reason),
		},
	})
}

// closeClientConnection closes current websocket connection 关闭当前 WebSocket 连接
func CloseConnection(ctx context.Context, clientIP string) int {
	clientIP = strings.TrimSpace(clientIP)
	if clientIP == "" {
		return 0
	}

	// Ensure websocket manager exists 确保 WebSocket 管理器已初始化
	websockets.Init(ctx)
	return websockets.WsManage.CloseClientConnections(clientIP)
}
