// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"context"
	"os"

	"github.com/Zany2/browserflow/backend/utility/llm"
	"github.com/Zany2/browserflow/backend/utility/state"
	"github.com/Zany2/browserflow/backend/utility/storage"
	"github.com/gogf/gf/v2/frame/g"
)

// ensureRuntime prepares shared chat dependencies 初始化聊天共享依赖
func ensureRuntime(ctx context.Context) (*storage.BoltDB, *llm.Client, error) {
	state.DBMu.Lock()
	defer state.DBMu.Unlock()

	// Database singleton 本地数据库单例
	if state.DB == nil {
		dbPath := os.Getenv("DB_PATH")
		if dbPath == "" {
			dbPath = g.Cfg().MustGet(ctx, "localStorage.path", "data/browserflow.db").String()
		}
		db, err := storage.NewBoltDB(dbPath)
		if err != nil {
			return nil, nil, err
		}
		state.DB = db
	}

	// LLM client singleton 大模型客户端单例
	if state.LLMClient == nil {
		state.LLMClient = llm.NewClient()
	}

	return state.DB, state.LLMClient, nil
}
