// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

// ControllerV1 chat controller 对话控制器
type ControllerV1 struct{}

// NewV1 creates chat controller 创建对话控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
