// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tasks

// ControllerV1 tasks controller 任务控制器
type ControllerV1 struct{}

// NewV1 creates tasks controller 创建任务控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
