// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package automa

// ControllerV1 automa controller Automa 控制器
type ControllerV1 struct{}

// NewV1 creates automa controller 创建 Automa 控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
