// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package browser

// ControllerV1 browser controller 浏览器控制器
type ControllerV1 struct{}

// NewV1 creates browser controller 创建浏览器控制器
func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
