// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// automaPackagesDao is the data access object for the table automa_packages.
// You can define custom methods on it to extend its functionality as needed.
type automaPackagesDao struct {
	*internal.AutomaPackagesDao
}

var (
	// AutomaPackages is a globally accessible object for table automa_packages operations.
	AutomaPackages = automaPackagesDao{internal.NewAutomaPackagesDao()}
)

// Add your custom methods and functionality below.
