// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// automaWorkflowsDao is the data access object for the table automa_workflows.
// You can define custom methods on it to extend its functionality as needed.
type automaWorkflowsDao struct {
	*internal.AutomaWorkflowsDao
}

var (
	// AutomaWorkflows is a globally accessible object for table automa_workflows operations.
	AutomaWorkflows = automaWorkflowsDao{internal.NewAutomaWorkflowsDao()}
)

// Add your custom methods and functionality below.
