// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// clientsDao is the data access object for the table clients.
// You can define custom methods on it to extend its functionality as needed.
type clientsDao struct {
	*internal.ClientsDao
}

var (
	// Clients is a globally accessible object for table clients operations.
	Clients = clientsDao{internal.NewClientsDao()}
)

// Add your custom methods and functionality below.
