// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// clientMachinesDao is the data access object for the table client_machines.
// You can define custom methods on it to extend its functionality as needed.
type clientMachinesDao struct {
	*internal.ClientMachinesDao
}

var (
	// ClientMachines is a globally accessible object for table client_machines operations.
	ClientMachines = clientMachinesDao{internal.NewClientMachinesDao()}
)

// Add your custom methods and functionality below.
