// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodeGroupsDao is the data access object for the table node_groups.
// You can define custom methods on it to extend its functionality as needed.
type nodeGroupsDao struct {
	*internal.NodeGroupsDao
}

var (
	// NodeGroups is a globally accessible object for table node_groups operations.
	NodeGroups = nodeGroupsDao{internal.NewNodeGroupsDao()}
)

// Add your custom methods and functionality below.
