// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodeWorkflowsDao is the data access object for the table node_workflows.
// You can define custom methods on it to extend its functionality as needed.
type nodeWorkflowsDao struct {
	*internal.NodeWorkflowsDao
}

var (
	// NodeWorkflows is a globally accessible object for table node_workflows operations.
	NodeWorkflows = nodeWorkflowsDao{internal.NewNodeWorkflowsDao()}
)

// Add your custom methods and functionality below.
