// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodeCommandsDao is the data access object for the table node_commands.
// You can define custom methods on it to extend its functionality as needed.
type nodeCommandsDao struct {
	*internal.NodeCommandsDao
}

var (
	// NodeCommands is a globally accessible object for table node_commands operations.
	NodeCommands = nodeCommandsDao{internal.NewNodeCommandsDao()}
)

// Add your custom methods and functionality below.
