// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodePackagesDao is the data access object for the table node_packages.
// You can define custom methods on it to extend its functionality as needed.
type nodePackagesDao struct {
	*internal.NodePackagesDao
}

var (
	// NodePackages is a globally accessible object for table node_packages operations.
	NodePackages = nodePackagesDao{internal.NewNodePackagesDao()}
)

// Add your custom methods and functionality below.
