// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodeEventsDao is the data access object for the table node_events.
// You can define custom methods on it to extend its functionality as needed.
type nodeEventsDao struct {
	*internal.NodeEventsDao
}

var (
	// NodeEvents is a globally accessible object for table node_events operations.
	NodeEvents = nodeEventsDao{internal.NewNodeEventsDao()}
)

// Add your custom methods and functionality below.
