// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// nodeGroupMembersDao is the data access object for the table node_group_members.
// You can define custom methods on it to extend its functionality as needed.
type nodeGroupMembersDao struct {
	*internal.NodeGroupMembersDao
}

var (
	// NodeGroupMembers is a globally accessible object for table node_group_members operations.
	NodeGroupMembers = nodeGroupMembersDao{internal.NewNodeGroupMembersDao()}
)

// Add your custom methods and functionality below.
