// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// taskRecordFilesDao is the data access object for the table task_record_files.
// You can define custom methods on it to extend its functionality as needed.
type taskRecordFilesDao struct {
	*internal.TaskRecordFilesDao
}

var (
	// TaskRecordFiles is a globally accessible object for table task_record_files operations.
	TaskRecordFiles = taskRecordFilesDao{internal.NewTaskRecordFilesDao()}
)

// Add your custom methods and functionality below.
