// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// taskAttemptsDao is the data access object for the table task_attempts.
// You can define custom methods on it to extend its functionality as needed.
type taskAttemptsDao struct {
	*internal.TaskAttemptsDao
}

var (
	// TaskAttempts is a globally accessible object for table task_attempts operations.
	TaskAttempts = taskAttemptsDao{internal.NewTaskAttemptsDao()}
)

// Add your custom methods and functionality below.
