// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// taskQueueDao is the data access object for the table task_queue.
// You can define custom methods on it to extend its functionality as needed.
type taskQueueDao struct {
	*internal.TaskQueueDao
}

var (
	// TaskQueue is a globally accessible object for table task_queue operations.
	TaskQueue = taskQueueDao{internal.NewTaskQueueDao()}
)

// Add your custom methods and functionality below.
