// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Zany2/browserflow/backend/internal/dao/internal"
)

// taskRecordsDao is the data access object for the table task_records.
// You can define custom methods on it to extend its functionality as needed.
type taskRecordsDao struct {
	*internal.TaskRecordsDao
}

var (
	// TaskRecords is a globally accessible object for table task_records operations.
	TaskRecords = taskRecordsDao{internal.NewTaskRecordsDao()}
)

// Add your custom methods and functionality below.
